package com.example.doll;

public class DollModConstants {
	public static final String MOD_ID = "doll-mod";
	public static final String DOLL_ENTITY_ID = "doll";
	public static final String DOLL_TIER1_EGG_ID = "doll_egg_s1";
	public static final String DOLL_TIER2_EGG_ID = "doll_egg_s2";
	public static final String DOLL_TIER3_EGG_ID = "doll_egg_s3";
	public static final String DOLL_TIER4_EGG_ID = "doll_egg_s4";
	public static final String DOLL_TIER5_EGG_ID = "doll_egg_s5";
	public static final String WARDEN_DOLL_EGG_ID = "warden_doll_egg";
	public static final String PALE_DOLL_EGG_ID = "pale_doll_egg";
	public static final String NETHER_DOLL_EGG_ID = "nether_doll_egg";
	public static final String PALE_DOLL_HEAD_ID = "pale_doll_head";
	public static final String PALE_DOLL_HEAD_ENTITY_ID = "pale_doll_head_entity";
	public static final String WARDEN_DOLL_HEAD_ID = "warden_doll_head";
	public static final String WARDEN_DOLL_HEAD_ENTITY_ID = "warden_doll_head_entity";
	public static final String NETHER_DOLL_HEAD_ID = "nether_doll_head";
	public static final String NETHER_DOLL_HEAD_ENTITY_ID = "nether_doll_head_entity";
	public static final String ENDER_DOLL_EGG_ID = "ender_doll_egg";
	public static final String ENDER_DOLL_HEAD_ID = "ender_doll_head";
	public static final String ENDER_DOLL_HEAD_ENTITY_ID = "ender_doll_head_entity";
	public static final String SEA_DOLL_EGG_ID = "sea_doll_egg";
	public static final String SEA_DOLL_HEAD_ID = "sea_doll_head";
	public static final String SEA_DOLL_HEAD_ENTITY_ID = "sea_doll_head_entity";
	public static final String FOREST_DOLL_EGG_ID = "forest_doll_egg";
	public static final String FOREST_DOLL_HEAD_ID = "forest_doll_head";
	public static final String FOREST_DOLL_HEAD_ENTITY_ID = "forest_doll_head_entity";
	public static final String SCULK_SHRINE_ID = "sculk_shrine";
	public static final String SCULK_SHRINE_ENTITY_ID = "sculk_shrine_entity";
	public static final String WARDEN_DOLL_ENTITY_ID = "wild_warden_doll";
	public static final String WARDEN_DOLL_SYNTHESIS_RECIPE_ID = "warden_doll_synthesis";
	public static final String DOLL_SCREEN_HANDLER_ID = "doll_inventory";
	public static final String DOLL_BATON_ID = "doll_baton";
	public static final String DOLL_CONTROL_PANEL_ID = "doll_panel";
	public static final String ROCK_ANVIL_ID = "rock_anvil";
	public static final String CHIPPED_ROCK_ANVIL_ID = "chipped_rock_anvil";
	public static final String DAMAGED_ROCK_ANVIL_ID = "damaged_rock_anvil";
	public static final String NETWORK_MODE_SELECT_ID = "select_mode";
}
